name: autofix.ci

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}

jobs:
  autofix:
    name: Format code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [24]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Format code
        run: pnpm run format
      - name: Run autofix-ci
        uses: autofix-ci/action@v1
        with:
          fail-fast: false
